language: python

python:
 - 2.7

install:
  - pip install pipenv
  - pipenv install

env:
  - PULLSBURY_SETTINGS="./settings.py"

script:
  - pipenv install coverage
  - pipenv run nosetests --with-coverage --cover-xml
  - pipenv run coverage xml

after_success:
  - ls
  - pipenv install codecov
  - pipenv run codecov

sudo: false

notifications:
  email:
    on_failure: change
