language: python

python:
 - 3.6

install:
  - pip install pipenv
  - pipenv install
  - pipenv install --dev

script:
  - env -u PULLSBURY_SETTINGS
  - pipenv run nosetests --with-coverage --cover-xml
  - pipenv run coverage xml

after_success:
  - pipenv run codecov

sudo: false

notifications:
  email:
    on_failure: change
