language: python

python:
 - "2.7"

install:
  - "pip install pipenv"
  - "pipenv install --two"

env:
  - PULLSBURY_SETTINGS="./settings.py"

script: "pipenv run nosetests"

sudo: false

notifications:
  email:
    on_failure: change
