apiVersion: v1
kind: ServiceAccount
metadata:
  name: pullsbury-gitboy
  namespace: pullsbury-gitboy
  annotations:
    iam.gke.io/gcp-service-account: pullsbury-gitboy-sa@freshbooks-builds.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pullsbury-gitboy
  namespace: pullsbury-gitboy
  labels:
    app: pullsbury-gitboy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pullsbury-gitboy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: pullsbury-gitboy
    spec:
      serviceAccountName: pullsbury-gitboy
      nodeSelector:
        note_type: tooling-slaves-gke-metadata-enabled
      containers:
      - name: pullsbury-gitboy
        image: gcr.io/freshbooks-builds/pullsbury-gitboy:APP_VERSION
        env:
        - name: PULLSBURY_SETTINGS
          value: /code/k8s_settings.py
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: pullsbury-gitboy-nodeport-service
  namespace: pullsbury-gitboy
spec:
  type: NodePort
  selector:
    app: pullsbury-gitboy
  ports:
  - nodePort: 32070
    port: 5000
    targetPort: 5000
