apiVersion: v1
kind: Namespace
metadata:
  name: pullsbury-gitboy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
  namespace: pullsbury-gitboy
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - configmaps
  - deployments
  - serviceaccounts
  - services
  - replicasets
  verbs:
  - get
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer
  namespace: pullsbury-gitboy
subjects:
- kind: ServiceAccount
  name: default
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer
